---
- name: Install apache & mysql & php
  hosts: web
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Install apache2"
      package: name=httpd state=present
    - name: "Install php-cli"
      package: name=php-cli state=present
    - name: "Install php-gd"
      package: name=php-gd state=present
    - name: "Install php-mysql"
      package: name=php-mysql state=present
    - name: "Install mysqlserver"
      package: name=mysql-server state=present
